{{- if .Values.manager.enabled }}
{{- if and .Values.clusterScoped .Values.manager.prometheus }}
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: dmo-controller-manager
  name: dmo-controller-manager-metrics-monitor
spec:
  endpoints:
    - path: /metrics
      port: https
  selector:
    matchLabels:
      control-plane: dmo-controller-manager
{{- end }}
{{- end }}
