{{- if .Values.manager.enabled }}
{{- if .Values.manager.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.manager.serviceAccount.name }}
  labels:
    app.kubernetes.io/component: manager
    {{- include "fybrik.labels" . | nindent 4 }}
  {{- with .Values.manager.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
