{{- if .Values.manager.enabled }}
{{- if .Values.clusterScoped }}
apiVersion: {{ include "fybrik.certManagerApiVersion" . }}
kind: Issuer
metadata:
  name: dmo-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}

---
apiVersion: {{ include "fybrik.certManagerApiVersion" . }}
kind: Certificate
metadata:
  name: dmo-serving-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
  - dmo-webhook-service.{{ .Release.Namespace }}.svc
  - dmo-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: dmo-selfsigned-issuer
  secretName: dmo-webhook-server-cert
{{- end }}
{{- end }}
