apiVersion: app.fybrik.io/v1alpha1
kind: FybrikModule
metadata:
  name: arrow-flight-module
  labels:
    name: arrow-flight-module
    version: latest # semantic version
spec:
  type: service
  chart:
    name: ghcr.io/fybrik/arrow-flight-module-chart:0.6.0
    values:
      image.tag: 0.6.0
  capabilities:
    - capability: read
      scope: workload
      api:
        connection:
          name: fybrik-arrow-flight
          fybrik-arrow-flight:
            hostname: "{{ .Release.Name }}.{{ .Release.Namespace }}"
            port: 80
            scheme: grpc
      supportedInterfaces:
        - source:
            protocol: s3
            dataformat: parquet
        - source:
            protocol: s3
            dataformat: csv
    - capability: write
      scope: workload
      api:
        connection:
          name: fybrik-arrow-flight
          fybrik-arrow-flight:
            hostname: "{{ .Release.Name }}.{{ .Release.Namespace }}"
            port: 80
            scheme: grpc
      supportedInterfaces:
        - sink:
            protocol: s3
            dataformat: parquet

