# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0
apiVersion: app.fybrik.io/v1beta1
kind: FybrikModule
metadata:
  name: implicit-copy-stream
  labels:
    name: implicit-copy-stream
    version: 0.8.0
spec:
  type: service
  capabilities:
    - capability: copy
      supportedInterfaces:
        - source:
            protocol: kafka
            dataformat: json
          sink:
            protocol: s3
            dataformat: parquet
        - source:
            protocol: kafka
            dataformat: avro
          sink:
            protocol: s3
            dataformat: parquet
      actions:
        - name: RedactAction
        - name: RemoveAction
  chart:
    name: ghcr.io/fybrik/fybrik-implicit-copy-stream:0.8.0
  statusIndicators:
    - kind: StreamTransfer
      successCondition: status.status == SUCCEEDED
      failureCondition: status.status == FAILED
      errorMessage: status.error
