# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

apiVersion: motion.fybrik.io/v1alpha1
kind: StreamTransfer
metadata:
  name: {{ .Release.Name }}
spec:
{{- if and (.Values.assets) (eq (len .Values.assets) 1) -}}
{{- with $asset := (index .Values.assets 0) }}
{{- if and ($asset.args) (eq (len $asset.args) 2) -}}
  {{- with index $asset.args 0 }}
  source:
    kafka:
      kafkaBrokers: {{ .connection.kafka.bootstrap_servers | quote }}
      schemaRegistryURL: {{ .connection.kafka.schema_registry | quote }}
      kafkaTopic: {{ .connection.kafka.topic_name | quote }}
      dataFormat: {{ .format | quote }}
      # user: "demo-consumer" # can be taken from vault
      # password: "" # can be taken from vault
      createSnapshot: false
      sslTruststore: {{ .connection.kafka.ssl_truststore | quote }}
      sslTruststoreLocation: /opt/spark/work-dir/ca.p12
      sslTruststorePassword: {{ .connection.kafka.ssl_truststore_password | quote }}
      securityProtocol: {{ .connection.kafka.security_protocol | quote }}
      saslMechanism: {{ .connection.kafka.sasl_mechanism | quote }}
      keyDeserializer: {{ .connection.kafka.key_deserializer | quote }}
      valueDeserializer: {{ .connection.kafka.value_deserializer | quote }}
      {{ if .vault.read }}
      vault:
{{ toYaml .vault.read | indent 8 }}
      {{ end }}
  {{- end }}
  {{- with index $asset.args 1 }}
  destination:
    s3:
      endpoint: {{ .connection.s3.endpoint | quote }}
      bucket: {{ .connection.s3.bucket | quote}}
      objectKey: {{ .connection.s3.object_key | quote }}
      dataFormat: {{ .format | quote}}
      {{ if .vault.write }}
      vault:
{{ toYaml .vault.write | indent 8 }}
      {{ end }}
  {{- end }}
  {{- end }}
  {{- if .transformations }}
  transformation:
  {{- $redactColumns := list -}}
  {{- $removeColumns := list -}}
  {{- range .transformations -}}
    {{- if eq .name "RedactAction" -}}
      {{- $redactColumns = .RedactAction.columns -}}
    {{- end -}}
    {{- if eq .name "RemoveAction" -}}
      {{- $removeColumns = .RemoveAction.columns -}}
    {{- end -}}
  {{- end -}}
  {{- if $redactColumns }}
    - action: "RedactColumns"
      name: "redacting columns: {{ $redactColumns }}"
      columns:
        {{- range $redactColumns}}
        - {{ . }}
        {{- end }}
      options:
        redactValue: "XXXXX"
  {{- end }}
  {{- if $removeColumns }}
    - action: "RemoveColumns"
      name: "removing columns: {{ $removeColumns }}"
      columns:
        {{- range $removeColumns}}
        - {{ . }}
        {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- else }}
  source:
  destination:
  {{- end }}
  triggerInterval: "10 seconds"
  {{ if .Values.image }}
  image: {{ .Values.image | quote }}
  {{ end }}
  {{ if .Values.imagePullPolicy }}
  imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
  {{ end }}
  noFinalizer: {{ .Values.noFinalizer }}
  readDataType: {{ .Values.readDataType | quote}}
  writeDataType: {{ .Values.writeDataType | quote }}
  writeOperation: {{ .Values.writeOperation | quote }}
